name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TELEMETRY_DISABLED: 1

    strategy:
      matrix:
        node-version: ['lts/-2', 'lts/-1', 'lts/*', 'current']
        experimental: [false]
        include:
          - node-version: current
            experimental: true
        exclude:
          - node-version: current
            experimental: false
      fail-fast: true

    continue-on-error: ${{ matrix.experimental }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          NODE_ENV=development pnpm install --frozen-lockfile
          pnpm husky install

      - name: Cache Turborepo
        uses: actions/cache@v4
        with:
          path: |
            .turbo
            node_modules/.cache/turbo
            node_modules/.cache/tsc
            node_modules/.cache/biome
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Validate
        run: pnpm turbo lint typecheck build test
        env:
          NODE_ENV: production
          VITEST_SEGFAULT_RETRY: 3

  test-publish:
    needs: validate
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: Install dependencies
        run: NODE_ENV=development pnpm install --frozen-lockfile

      - name: Test Package Publishing
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "always-auth=true" >> .npmrc
          NODE_ENV=production pnpm publish --dry-run --no-git-checks
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
